<?php
echo '<div class="col-lg-9">';
echo '<div class="box border-bottom-0">';
echo '<h2>Rincian Pesanan</h2>';
echo '<table class="table">';
echo '<thead>';
echo '<tr>';
echo '<th width="40%">Nama Product</th>';
echo '<th width="20%">Quantity</th>';
echo '<th class="text-right">Unit price</th>';
echo '<th class="text-right">Total</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody>';
if(!empty($cart)) {
    $total = 0;
    foreach ($cart as $items) {
    echo '<tr>';
    echo '<td>' . $items['name']. '</td>';
    echo '<td>'; 
    echo $items['qty'];  
    echo '<input type="hidden" class="item-rowid" name="rowid"' . $items['id'] .'" . value="'. $items['rowid'] . '">';
    echo '</td>';
    echo '<td class="text-right">';
    echo number_format($items['price'], 2); 
    echo '</td>';
    echo '<td class="text-right">'; 
    echo number_format($items['qty']* $items['price'], 2) ; 
    echo '</td>'; 
    echo '</tr>';
    $total += ($items['qty']*$items['price']);
    }
} else {
    $total = 0;
    echo '<tr>';
    echo '<td colspan="4">';
    echo 'Cart Kosong';
    echo '<td>';
    echo '</tr>';
}
echo '</tbody>';
echo '<tfoot>';
echo '<tr>';
echo '<td colspan="3"><b>Order Total:</b></td>';
echo '<td class="text-right"<th><b>Rp.' . number_format ($total, 2) . '</b></th> </td>';
echo '</tr>';
echo '</tfoot>';
echo '</table>';
echo '<h2>Rincian Pemesan</h2>';
echo '<div class="row">';
echo '<div class="col-sm-3">';
echo '<div class="form-group">';
echo '<label for="firstname"><b>Firstname :</b></label><br />';
echo $user_data['vcfname'];
echo '</div>';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<div class="form-group">';
echo '<label for="lastname"><b>Lastname:</b></label><br />';
echo $user_data['vclname'];
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12">';
echo '<div class="form-group">';
echo '<label for="company"><b>Street :</b></label><br />';
echo $user_data['vcstreet'];
echo '</div>';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<div class="form-group">';
echo '<label for="selectprop"><b>State :</b></label><br />';
// echo $user_data['vcstate'];
echo $user_data['nama_state'];
echo '</div>';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<div class="form-group">';
echo '<label for="city"><b>City :</b></label><br />';
// echo $user_data['vccity'];
echo $user_data['nama_city'];
echo '</div>';
echo '</div>';
echo '<div class="col-sm-12">';
echo '<div id="jnetype">';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<div class="form-group">';
echo '<label for="phone"><b>Telephone :</b></label><br />';
echo $user_data['inttelephone'];
echo '</div>';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<div class="form-group">';
echo '<label for="email"><b>Email :</b></label><br />';
echo $user_data['vcemail'];
echo '</div>';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<div class="form-group">';
echo '<label for="selmethod"><b>Payment :</b></label><br />';
echo $user_data['vcpayment'];
echo '</div>';
echo '</div>';
echo '<div class="box-footer d-flex flex-wrap align-items-center justify-content-between">';
echo '<div class="left-col"><a href="' . base_url() . 'order/payment" class="btn btn-template-outlined"><i class="fa fa-chevron-left"></i>
Kembali</a></div>';
echo '<div class="right-col" style="padding-left:83%">';
if(!empty($cart)) {
echo '<a href="'. base_url() . 'order/payment"  class="btn btn-template-outlined">Lanjutkan <i class="fa fa-chevron-right"></i></a>';
}
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';

echo '<div class="col-lg-3">';
echo '<div id="order-summary" class="box mt-0 mb-4 p-0">';
echo '<div class="box-header mt-0">';
echo '<h3>Rincian Pesanan</h3>';
echo '</div>';
echo '<p class="text-muted">Pengiriman dan biaya tambahan dihitung berdasarkan nilai yang Anda masukkan.</p>';
echo '<div class="table-responsive">';
echo '<table class="table">';
echo '<tbody>';
echo '<tr>';
echo '<td>Subtotal</td>';
echo '<th><b>Rp.' . number_format ($total, 2) . '</b></th>';
echo '</tr>';
echo '<tr>';
echo '<td>Ongkos Kirim</td>';
echo '<th><b>Rp.' . number_format ($user_data['ongkir'], 2) . '</b></th>';
echo '</tr>';
echo '<tr class="total">';
echo '<td>Total</td>';
echo '<th><b>Rp.' . number_format ($total+$user_data['ongkir'], 2) . '</b></th>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '</div>';
echo '</div>';